### PR TITLE
Ensure fallback HTTP 500 returned

### PR DESCRIPTION
**Pull request by LoneRifle**
* Create a test that verifies that deleting a stop with existing trips
will result in 500

* Ensure that we actually return the error we created when all else fails

### CODE REVIEW

**Comment by xkjyeah** [comment]
500 is a bad error because it's usually reserved for unexpected errors.

Maybe 400?

**Comment by xkjyeah** [comment]
Or better: 409 Conflict

**Comment by LoneRifle** [comment]
We assume that the error is bad - notice that the line is invoked if we have run out of every other possible option, including 400s and whatnot.

**Comment by xkjyeah** [comment]
But your test case specifically checks for 500?

**Comment by LoneRifle** [comment]
Er, yes, why? If we deliberately do something that blows up that (in the test case) we know will not be covered by any of the other options, we should expect a 500 to be returned.

**Comment by LoneRifle** [comment]
Right, there are two things we're trying to do here:

* we're trying to verify what happens when we deliberately delete a stop which a trip has a dependency on. This, as @xkjyeah suggests, should return a 400 or 409, not a 500

* nonetheless, this PR is trying to fix a bug where an unexpected error is swallowed and not returned _at all_.

The second point has been addressed but not the first.

**Comment by joelchoo** [comment]
Looks good to me now!

**Pull request merged**
