### PR TITLE
User history grouping

### PR DESCRIPTION
**Pull request by LoneRifle**

### CODE REVIEW

**Comment by xkjyeah** [comment]
Dude, I'm still in favour of creating a secondary web server.

Or moving things to another endpoint, e.g. `/views/groupedUserHistory` (and then use `server.inject` from there)

Reasons as follows:
1. It only queries the public API, so it can't leak data from the database by accident
2. It doesn't change the public API schema
3. By breaking down the parts it makes everything more testable.

**Comment by LoneRifle** [comment]
This change doesn't contravene two of the reasons you've put forward, as far as i can tell.
2. This change adds to the schema by adding an optional flag, and doesn't break expectations for current clients
3. The increase in testing complexity is still fairly manageable

1 might be a valid point, but I really don't think we have that level of complexity such that this becomes a significant risk.

I really don't think the team has much appetite to create yet another service just to perform light transformations. Adding an extra service also adds another possible point of failure in the flow, and while I realise that SoundCloud has reaped the clean API benefits of having backends-for-frontends [1], we only have _one_ frontend to worry about anyway, and we are nowhere near the kind of complexity that SoundCloud faces to have to use such approaches to manage them.

Adding another endpoint which does almost the same thing as `user_history` could lead to complexity as a result of managing/preventing logic duplication, something I would rather spend on just adding the boolean flag to get the item grouping. 

There _will_ be some other endpoint that I _will_ fashion into a new separate one for the frontend - this is not the one.

References:
[1] https://www.thoughtworks.com/insights/blog/bff-soundcloud

**Comment by chuasweechin** [comment]
Hi Daniel,

Can you elaborate to me point #1 on the data leak risk from the DB?

Regards,
Chua Swee Chin

**Comment by LoneRifle** [comment]
I can answer that one. What he means is that if you build the transformations in a separate process, you avoid making changes to the public API, thereby avoiding the risk associated with doing so, the risk in this case being you accidentally make a change to the API that returns data you were not intending to return.

**Comment by chuasweechin** [comment]
That is a fair concern though, given that it is very hard to guard against
such mistakes through testing.
We won't want an accidental return of data that cause us problem down the
line.

**Comment by LoneRifle** [comment]
Exactly, but as I have pointed out, we are not at a point in terms of complexity to commit to having a transformations service. The gains from leakage mitigation may not be as large as you think, given that I could still be making changes to the public API in the course of work.

**Comment by chuasweechin** [comment]
Now i understand. Got it!

**Pull request merged**
